<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <AssemblyName>QuickCapture</AssemblyName>
    <Version>0.3.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/app.ico" />
    <Resource Include="Assets/app.png" />
    <PackageReference Include="ScreenRecorderLib" Version="7.0.1" />
  </ItemGroup>
</Project>
